// QUANGTHUONG AI — Setup script cho OpenClaw (Telegram AI bot CLI).
// GET /api/v1/llm/setup-openclaw?key=sk-bee-...&os=linux|mac|windows&small=...&medium=...&high=...&bot_token=...&user_id=...
// Style: banner, in FULL API key + Bot Token + User ID, backup config cũ, merge JSON qua python3,
// Configuration Complete banner + Summary, restart LaunchAgent (macOS), Next steps + docs link.
// Key ĐẦY ĐỦ luôn được in ra console — không truncate.

import { NextRequest } from "next/server";

const BASE_URL = "https://quangthuong-ai.vercel.app/api";
const DOCS_URL = "https://quangthuong-ai.vercel.app/api-keys";

function shellQuote(value: string) {
  return `'${value.replace(/'/g, `'"'"'`)}'`;
}

function psQuote(value: string) {
  return `'${value.replace(/'/g, `''`)}'`;
}

export async function GET(req: NextRequest) {
  const url = new URL(req.url);
  const key = url.searchParams.get("key")?.trim() ?? "";
  const os = (url.searchParams.get("os") || "mac").toLowerCase();
  const small = url.searchParams.get("small")?.trim() ?? "";
  const medium = url.searchParams.get("medium")?.trim() ?? "";
  const high = url.searchParams.get("high")?.trim() ?? "";
  const botToken = url.searchParams.get("bot_token")?.trim() ?? "";
  const userId = url.searchParams.get("user_id")?.trim() ?? "";

  if (!key || !small || !medium || !high) {
    return new Response(
      "# Thiếu tham số: cần key, small, medium, high\nexit 1\n",
      { status: 400, headers: { "content-type": "text/plain; charset=utf-8" } },
    );
  }
  // Chặn key rút gọn — script phải nhận key đầy đủ, không thì config sai => mọi request 401.
  if (key.includes("...") || !/^sk-bee-[A-Za-z0-9_-]{20,}$/.test(key)) {
    return new Response(
      "API key không hợp lệ. Hãy dán key ĐẦY ĐỦ (sk-bee-...) — không dùng dạng rút gọn.\n",
      { status: 400, headers: { "content-type": "text/plain; charset=utf-8" } },
    );
  }

  const isWindows = os === "windows" || os === "win";
  const body = isWindows
    ? buildPowerShell({ key, small, medium, high, botToken, userId })
    : buildPosix({ key, small, medium, high, botToken, userId });

  return new Response(body, {
    status: 200,
    headers: {
      "content-type": isWindows
        ? "text/plain; charset=utf-8"
        : "text/x-shellscript; charset=utf-8",
      "cache-control": "no-store",
    },
  });
}

// ===== POSIX (macOS / Linux) =====
function buildPosix(opts: {
  key: string;
  small: string; medium: string; high: string;
  botToken: string; userId: string;
}): string {
  // Cross-platform POSIX script — không phân biệt mac/linux tại server,
  // restart gateway qua `openclaw daemon restart` (launchd/systemd/schtasks tự xử lý).
  return [
    `#!/bin/sh`,
    `set -e`,
    ``,
    `BASE_URL=${shellQuote(BASE_URL)}`,
    `API_KEY=${shellQuote(opts.key)}`,
    `SMALL_MODEL=${shellQuote(opts.small)}`,
    `MEDIUM_MODEL=${shellQuote(opts.medium)}`,
    `HIGH_MODEL=${shellQuote(opts.high)}`,
    `BOT_TOKEN=${shellQuote(opts.botToken)}`,
    `TG_USER_ID=${shellQuote(opts.userId)}`,
    `DOCS_URL=${shellQuote(DOCS_URL)}`,
    `TS=$(date +%Y%m%d-%H%M%S)`,
    `CONFIG_DIR="$HOME/.openclaw"`,
    `CONFIG_FILE="$CONFIG_DIR/openclaw.json"`,
    ``,
    `CYAN=$(printf '\\033[36m')`,
    `GREEN=$(printf '\\033[32m')`,
    `YELLOW=$(printf '\\033[33m')`,
    `BOLD=$(printf '\\033[1m')`,
    `DIM=$(printf '\\033[2m')`,
    `RESET=$(printf '\\033[0m')`,
    ``,
    `printf '\\n'`,
    `printf '%s%s========================================%s\\n' "$BOLD" "$CYAN" "$RESET"`,
    `printf '%s%s   QUANGTHUONG AI OpenClaw Setup%s\\n' "$BOLD" "$CYAN" "$RESET"`,
    `printf '%s%s========================================%s\\n' "$BOLD" "$CYAN" "$RESET"`,
    `printf '\\n'`,
    `printf '%sEndpoint URL:%s %s\\n' "$BOLD" "$RESET" "$BASE_URL"`,
    `printf '%sAPI Key:%s      %s\\n' "$BOLD" "$RESET" "$API_KEY"`,
    `if [ -n "$BOT_TOKEN" ]; then`,
    `  printf '%sBot Token:%s    %s\\n' "$BOLD" "$RESET" "$BOT_TOKEN"`,
    `fi`,
    `if [ -n "$TG_USER_ID" ]; then`,
    `  printf '%sUser ID:%s      %s\\n' "$BOLD" "$RESET" "$TG_USER_ID"`,
    `fi`,
    `printf '%sModels:%s       small=%s · medium=%s · high=%s\\n' "$BOLD" "$RESET" "$SMALL_MODEL" "$MEDIUM_MODEL" "$HIGH_MODEL"`,
    `printf '\\n'`,
    ``,
    `mkdir -p "$CONFIG_DIR"`,
    ``,
    `#--- Backup ---`,
    `if [ -f "$CONFIG_FILE" ]; then`,
    `  cp "$CONFIG_FILE" "$CONFIG_FILE.backup.$TS"`,
    `  printf '  %s✓%s Backed up existing config: %s.backup.%s\\n' "$GREEN" "$RESET" "$CONFIG_FILE" "$TS"`,
    `  printf '%sUpdating existing config (only QUANGTHUONG models & telegram)...%s\\n' "$BOLD" "$RESET"`,
    `else`,
    `  printf '%sGenerating config...%s\\n' "$BOLD" "$RESET"`,
    `fi`,
    ``,
    `#--- Merge config qua python3 — schema CHUẨN OpenClaw (models.providers + agents.defaults + channels.telegram + env) ---`,
    `if ! command -v python3 >/dev/null 2>&1; then`,
    `  printf '  %s✗%s Cần python3 để merge config. Cài: %sbrew install python3%s (mac) hoặc %sapt install python3%s (linux)\\n' "$YELLOW" "$RESET" "$YELLOW" "$RESET" "$YELLOW" "$RESET"`,
    `  exit 1`,
    `fi`,
    `BASE_URL="$BASE_URL" API_KEY="$API_KEY" SMALL_MODEL="$SMALL_MODEL" MEDIUM_MODEL="$MEDIUM_MODEL" HIGH_MODEL="$HIGH_MODEL" BOT_TOKEN="$BOT_TOKEN" TG_USER_ID="$TG_USER_ID" CONFIG_FILE="$CONFIG_FILE" python3 - <<'PY'`,
    `import json, os`,
    `from pathlib import Path`,
    `p = Path(os.environ['CONFIG_FILE'])`,
    `try:`,
    `    data = json.loads(p.read_text()) if p.exists() else {}`,
    `except Exception:`,
    `    data = {}`,
    `if not isinstance(data, dict):`,
    `    data = {}`,
    ``,
    `BASE_URL = os.environ['BASE_URL'].rstrip('/')`,
    `API_KEY  = os.environ['API_KEY']`,
    `SMALL    = os.environ['SMALL_MODEL']`,
    `MEDIUM   = os.environ['MEDIUM_MODEL']`,
    `HIGH     = os.environ['HIGH_MODEL']`,
    `BOT      = os.environ.get('BOT_TOKEN', '').strip()`,
    `UID      = os.environ.get('TG_USER_ID', '').strip()`,
    `BASE_V1  = BASE_URL + '/v1'   # OpenAI/Anthropic adapter sẽ append /chat/completions hoặc /messages`,
    ``,
    `# ---- Clean up flat keys cũ (từ script bản trước) — schema OpenClaw không nhận ----`,
    `for legacy in ('base_url', 'api_key', 'telegram'):`,
    `    data.pop(legacy, None)`,
    `if isinstance(data.get('models'), dict):`,
    `    for legacy in ('small', 'medium', 'high'):`,
    `        data['models'].pop(legacy, None)`,
    ``,
    `def is_anthropic(m): return m.lower().startswith('claude')`,
    ``,
    `# ---- models.providers (tách 2 entry theo adapter, gom các model cùng họ) ----`,
    `data.setdefault('models', {})`,
    `data['models'].setdefault('providers', {})`,
    `chosen = [('small', SMALL), ('medium', MEDIUM), ('high', HIGH)]`,
    `oai_models = sorted({m for _, m in chosen if not is_anthropic(m)})`,
    `ant_models = sorted({m for _, m in chosen if is_anthropic(m)})`,
    `PROV_OAI = 'quangthuong-openai'`,
    `PROV_ANT = 'quangthuong-anthropic'`,
    `if oai_models:`,
    `    data['models']['providers'][PROV_OAI] = {`,
    `        'baseUrl': BASE_V1,`,
    `        'apiKey':  API_KEY,`,
    `        'auth':    'api-key',`,
    `        'api':     'openai-completions',`,
    `        'models':  [{'id': m, 'name': m} for m in oai_models],`,
    `    }`,
    `if ant_models:`,
    `    data['models']['providers'][PROV_ANT] = {`,
    `        'baseUrl': BASE_V1,`,
    `        'apiKey':  API_KEY,`,
    `        'auth':    'api-key',`,
    `        'api':     'anthropic-messages',`,
    `        'models':  [{'id': m, 'name': m} for m in ant_models],`,
    `    }`,
    ``,
    `def slug(m): return f"{PROV_ANT if is_anthropic(m) else PROV_OAI}/{m}"`,
    ``,
    `# ---- agents.defaults.models + primary + fallbacks ----`,
    `data.setdefault('agents', {}).setdefault('defaults', {})`,
    `data['agents']['defaults'].setdefault('models', {})`,
    `for _, m in chosen:`,
    `    data['agents']['defaults']['models'].setdefault(slug(m), {})`,
    `data['agents']['defaults'].setdefault('model', {})`,
    `data['agents']['defaults']['model']['primary'] = slug(HIGH)`,
    `# fallbacks: medium → small (dedupe, khác primary)`,
    `fb = []`,
    `for m in (MEDIUM, SMALL):`,
    `    s = slug(m)`,
    `    if s != slug(HIGH) and s not in fb:`,
    `        fb.append(s)`,
    `data['agents']['defaults']['model']['fallbacks'] = fb`,
    ``,
    `# ---- Telegram bot token (env.<KEY>) ----`,
    `if BOT:`,
    `    data.setdefault('env', {})`,
    `    data['env']['TELEGRAM_BOT_TOKEN'] = BOT`,
    ``,
    `# ---- channels.telegram.{enabled, allowFrom, dmPolicy} ----`,
    `if UID:`,
    `    data.setdefault('channels', {}).setdefault('telegram', {})`,
    `    tg = data['channels']['telegram']`,
    `    tg['enabled']  = True`,
    `    tg.setdefault('dmPolicy', 'allowlist')`,
    `    existing = tg.get('allowFrom') or []`,
    `    if UID not in existing:`,
    `        existing.append(UID)`,
    `    tg['allowFrom'] = existing`,
    ``,
    `p.write_text(json.dumps(data, indent=2, ensure_ascii=False) + '\\n')`,
    `PY`,
    `printf '  %s✓%s Created %s\\n\\n' "$GREEN" "$RESET" "$CONFIG_FILE"`,
    ``,
    `#--- Done banner ---`,
    `printf '%s%s========================================%s\\n' "$BOLD" "$GREEN" "$RESET"`,
    `printf '%s%s   Configuration Complete!%s\\n' "$BOLD" "$GREEN" "$RESET"`,
    `printf '%s%s========================================%s\\n' "$BOLD" "$GREEN" "$RESET"`,
    `printf '\\n'`,
    `printf '%sSummary:%s\\n' "$BOLD" "$RESET"`,
    `printf '  Config     : %s\\n' "$CONFIG_FILE"`,
    `printf '  Endpoint   : %s\\n' "$BASE_URL"`,
    `printf '  API Key    : %s\\n' "$API_KEY"`,
    `if [ -n "$BOT_TOKEN" ]; then`,
    `  printf '  Bot Token  : %s\\n' "$BOT_TOKEN"`,
    `fi`,
    `if [ -n "$TG_USER_ID" ]; then`,
    `  printf '  User ID    : %s\\n' "$TG_USER_ID"`,
    `fi`,
    `printf '  Small      : %s\\n' "$SMALL_MODEL"`,
    `printf '  Medium     : %s\\n' "$MEDIUM_MODEL"`,
    `printf '  High       : %s\\n' "$HIGH_MODEL"`,
    `printf '\\n'`,
    ``,
    `#--- Restart gateway (qua openclaw daemon — cross-platform: launchd/systemd/schtasks) ---`,
    `printf '%sRestarting gateway...%s\\n' "$BOLD" "$RESET"`,
    `if command -v openclaw >/dev/null 2>&1; then`,
    `  if openclaw daemon restart >/dev/null 2>&1; then`,
    `    printf '  %s✓%s Gateway restarted (openclaw daemon restart)\\n\\n' "$GREEN" "$RESET"`,
    `  elif openclaw daemon start >/dev/null 2>&1; then`,
    `    printf '  %s✓%s Gateway started (openclaw daemon start)\\n\\n' "$GREEN" "$RESET"`,
    `  else`,
    `    printf '  %s!%s Không restart tự động được — chạy: %sopenclaw daemon status%s để chẩn đoán\\n\\n' "$YELLOW" "$RESET" "$YELLOW" "$RESET"`,
    `  fi`,
    `else`,
    `  printf '  %s-%s openclaw CLI chưa có trong PATH — cài qua: %scurl -fsSL https://openclaw.ai/install.sh | bash%s\\n\\n' "$DIM" "$RESET" "$YELLOW" "$RESET"`,
    `fi`,
    ``,
    `printf '%sNext steps:%s\\n' "$BOLD" "$RESET"`,
    `if [ -n "$BOT_TOKEN" ] && [ -n "$TG_USER_ID" ]; then`,
    `  printf '  1. Mở Telegram và nhắn cho bot của bạn\\n'`,
    `  printf '  2. Nếu chưa chạy: %sopenclaw daemon start%s\\n' "$YELLOW" "$RESET"`,
    `else`,
    `  printf '  1. Bổ sung Bot Token & User ID trong %s nếu chưa có\\n' "$CONFIG_FILE"`,
    `  printf '  2. Chạy: %sopenclaw daemon start%s\\n' "$YELLOW" "$RESET"`,
    `fi`,
    `printf '\\n'`,
    `printf '%sDocumentation:%s %s\\n' "$DIM" "$RESET" "$DOCS_URL"`,
    `printf '\\n'`,
    ``,
  ].join("\n");
}

// ===== Windows PowerShell =====
function buildPowerShell(opts: {
  key: string;
  small: string; medium: string; high: string;
  botToken: string; userId: string;
}): string {
  return [
    `# QUANGTHUONG AI - OpenClaw Setup (Windows PowerShell)`,
    `$ErrorActionPreference = 'Stop'`,
    ``,
    `$BaseUrl    = ${psQuote(BASE_URL)}`,
    `$ApiKey     = ${psQuote(opts.key)}`,
    `$Small      = ${psQuote(opts.small)}`,
    `$Medium     = ${psQuote(opts.medium)}`,
    `$High       = ${psQuote(opts.high)}`,
    `$BotToken   = ${psQuote(opts.botToken)}`,
    `$TgUserId   = ${psQuote(opts.userId)}`,
    `$DocsUrl    = ${psQuote(DOCS_URL)}`,
    `$ts         = Get-Date -Format 'yyyyMMdd-HHmmss'`,
    `$configDir  = Join-Path $HOME '.openclaw'`,
    `$configFile = Join-Path $configDir 'openclaw.json'`,
    `if (-not (Test-Path $configDir)) { New-Item -ItemType Directory -Path $configDir | Out-Null }`,
    ``,
    `Write-Host ""`,
    `Write-Host "========================================" -ForegroundColor Cyan`,
    `Write-Host "   QUANGTHUONG AI OpenClaw Setup"        -ForegroundColor Cyan`,
    `Write-Host "========================================" -ForegroundColor Cyan`,
    `Write-Host ""`,
    `Write-Host "Endpoint URL: $BaseUrl"`,
    `Write-Host "API Key:      $ApiKey"`,
    `if ($BotToken) { Write-Host "Bot Token:    $BotToken" }`,
    `if ($TgUserId) { Write-Host "User ID:      $TgUserId" }`,
    `Write-Host "Models:       small=$Small | medium=$Medium | high=$High"`,
    `Write-Host ""`,
    ``,
    `if (Test-Path $configFile) {`,
    `  Copy-Item $configFile "$configFile.backup.$ts" -Force`,
    `  Write-Host "  [OK] Backed up existing config: $configFile.backup.$ts" -ForegroundColor Green`,
    `  Write-Host "Updating existing config (only QUANGTHUONG models & telegram)..."`,
    `} else {`,
    `  Write-Host "Generating config..."`,
    `}`,
    ``,
    `if (Test-Path $configFile) {`,
    `  try { $data = Get-Content $configFile -Raw | ConvertFrom-Json -AsHashtable } catch { $data = @{} }`,
    `} else { $data = @{} }`,
    `if (-not $data) { $data = @{} }`,
    ``,
    `# ---- Clean up flat keys cũ (script bản trước) — schema OpenClaw không nhận ----`,
    `foreach ($k in @('base_url','api_key','telegram')) { if ($data.ContainsKey($k)) { $data.Remove($k) | Out-Null } }`,
    `if ($data.models -is [hashtable]) {`,
    `  foreach ($k in @('small','medium','high')) { if ($data.models.ContainsKey($k)) { $data.models.Remove($k) | Out-Null } }`,
    `}`,
    ``,
    `$BaseV1 = $BaseUrl.TrimEnd('/') + '/v1'`,
    `function IsAnth([string]$m) { return $m.ToLower().StartsWith('claude') }`,
    `$chosen = @(@{role='small'; id=$Small}, @{role='medium'; id=$Medium}, @{role='high'; id=$High})`,
    `$oai = ($chosen | Where-Object { -not (IsAnth $_.id) } | ForEach-Object { $_.id } | Select-Object -Unique | Sort-Object)`,
    `$ant = ($chosen | Where-Object {       (IsAnth $_.id) } | ForEach-Object { $_.id } | Select-Object -Unique | Sort-Object)`,
    `$PROV_OAI = 'quangthuong-openai'`,
    `$PROV_ANT = 'quangthuong-anthropic'`,
    ``,
    `if (-not $data.models) { $data.models = @{} }`,
    `if (-not $data.models.providers) { $data.models.providers = @{} }`,
    `if ($oai.Count -gt 0) {`,
    `  $data.models.providers[$PROV_OAI] = @{ baseUrl=$BaseV1; apiKey=$ApiKey; auth='api-key'; api='openai-completions'; models=@($oai | ForEach-Object { @{ id=$_; name=$_ } }) }`,
    `}`,
    `if ($ant.Count -gt 0) {`,
    `  $data.models.providers[$PROV_ANT] = @{ baseUrl=$BaseV1; apiKey=$ApiKey; auth='api-key'; api='anthropic-messages'; models=@($ant | ForEach-Object { @{ id=$_; name=$_ } }) }`,
    `}`,
    ``,
    `function Slug([string]$m) { if (IsAnth $m) { return "$PROV_ANT/$m" } else { return "$PROV_OAI/$m" } }`,
    ``,
    `if (-not $data.agents) { $data.agents = @{} }`,
    `if (-not $data.agents.defaults) { $data.agents.defaults = @{} }`,
    `if (-not $data.agents.defaults.models) { $data.agents.defaults.models = @{} }`,
    `foreach ($c in $chosen) { $s = Slug $c.id; if (-not $data.agents.defaults.models.ContainsKey($s)) { $data.agents.defaults.models[$s] = @{} } }`,
    `if (-not $data.agents.defaults.model) { $data.agents.defaults.model = @{} }`,
    `$primary = Slug $High; $data.agents.defaults.model.primary = $primary`,
    `$fb = @(); foreach ($m in @($Medium, $Small)) { $s = Slug $m; if ($s -ne $primary -and -not ($fb -contains $s)) { $fb += $s } }`,
    `$data.agents.defaults.model.fallbacks = $fb`,
    ``,
    `if ($BotToken) {`,
    `  if (-not $data.env) { $data.env = @{} }`,
    `  $data.env.TELEGRAM_BOT_TOKEN = $BotToken`,
    `}`,
    `if ($TgUserId) {`,
    `  if (-not $data.channels) { $data.channels = @{} }`,
    `  if (-not $data.channels.telegram) { $data.channels.telegram = @{} }`,
    `  $tg = $data.channels.telegram`,
    `  $tg.enabled = $true`,
    `  if (-not $tg.dmPolicy) { $tg.dmPolicy = 'allowlist' }`,
    `  $existing = @(); if ($tg.allowFrom) { $existing = @($tg.allowFrom) }`,
    `  if (-not ($existing -contains $TgUserId)) { $existing += $TgUserId }`,
    `  $tg.allowFrom = $existing`,
    `}`,
    ``,
    `$data | ConvertTo-Json -Depth 12 | Set-Content -Path $configFile -Encoding UTF8`,
    `Write-Host "  [OK] Created $configFile" -ForegroundColor Green`,
    `Write-Host ""`,
    ``,
    `Write-Host "========================================" -ForegroundColor Green`,
    `Write-Host "   Configuration Complete!"               -ForegroundColor Green`,
    `Write-Host "========================================" -ForegroundColor Green`,
    `Write-Host ""`,
    `Write-Host "Summary:"`,
    `Write-Host "  Config     : $configFile"`,
    `Write-Host "  Endpoint   : $BaseUrl"`,
    `Write-Host "  API Key    : $ApiKey"`,
    `if ($BotToken) { Write-Host "  Bot Token  : $BotToken" }`,
    `if ($TgUserId) { Write-Host "  User ID    : $TgUserId" }`,
    `Write-Host "  Small      : $Small"`,
    `Write-Host "  Medium     : $Medium"`,
    `Write-Host "  High       : $High"`,
    `Write-Host ""`,
    `Write-Host "Restarting gateway..." -ForegroundColor White`,
    `if (Get-Command openclaw -ErrorAction SilentlyContinue) {`,
    `  try { openclaw daemon restart 2>$null | Out-Null; Write-Host "  [OK] Gateway restarted (openclaw daemon restart)" -ForegroundColor Green }`,
    `  catch {`,
    `    try { openclaw daemon start 2>$null | Out-Null; Write-Host "  [OK] Gateway started (openclaw daemon start)" -ForegroundColor Green }`,
    `    catch { Write-Host "  [!] Không restart được — chạy: openclaw daemon status" -ForegroundColor Yellow }`,
    `  }`,
    `} else {`,
    `  Write-Host "  [-] openclaw CLI chưa có — cài qua: irm https://openclaw.ai/install.ps1 | iex" -ForegroundColor DarkGray`,
    `}`,
    `Write-Host ""`,
    `Write-Host "Next steps:"`,
    `if ($BotToken -and $TgUserId) {`,
    `  Write-Host "  1. Mở Telegram và nhắn cho bot của bạn"`,
    `  Write-Host "  2. Nếu chưa chạy: openclaw daemon start"`,
    `} else {`,
    `  Write-Host "  1. Bổ sung Bot Token & User ID trong $configFile nếu chưa có"`,
    `  Write-Host "  2. Chạy: openclaw daemon start"`,
    `}`,
    `Write-Host ""`,
    `Write-Host "Documentation: $DocsUrl" -ForegroundColor DarkGray`,
    `Write-Host ""`,
  ].join("\r\n");
}
